backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # Where uploaded images go (relative to repo root)
public_folder: "static/images/uploads"   # How those images are referenced in the site

media_library:
  name: uploadcare
  config: {}

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.md"
        label: "Homepage Content"
        name: "home"
        fields:
          - { name: "title", label: "Event Title", widget: "string" }
          - { name: "date", label: "Date", widget: "string" }
          - { name: "location", label: "Location", widget: "string" }
          - { name: "button_1_text", label: "First Button Text", widget: "string" }
          - { name: "button_2_text", label: "Second Button Text", widget: "string" }
          - { name: "social_links", label: "Social Links", widget: "list", fields: [
              { name: "name", label: "Name", widget: "string" },
              { name: "url", label: "URL", widget: "string" }
            ] }