backend:
  name: git-gateway
  branch: main # Your default branch
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          # Add all your fields here
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Dates", name: "dates", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - label: "Buttons"
            name: "buttons"
            widget: "list"
            fields:
              - {label: "Button Text", name: "text", widget: "string"}
              - {label: "Button Link", name: "link", widget: "string"}
              - {label: "Button Target", name: "target", widget: "string", default: "_blank"}
          - label: "Floating Buttons"
            name: "floating_buttons"
            widget: "list"
            fields:
              - {label: "Button Text", name: "text", widget: "string"}
              - {label: "Button Link", name: "link", widget: "string"}
          - {label: "Social Links", name: "social", widget: "object", fields: [
              {label: "Instagram", name: "instagram", widget: "string"},
              {label: "Facebook", name: "facebook", widget: "string"}
            ]}

      - name: "about_darklight"
        label: "About Darklight"
        file: "content/about_darklight.md"
        fields:
          - {label: "Logo Image", name: "logo", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}

      - name: "about_resonate"
        label: "About Resonate"
        file: "content/about_resonate.md"
        fields:
          - {label: "Logo Image", name: "logo", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
          - label: "Performers"
            name: "performers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}