backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"

# Media storage
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Dates", name: "dates", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
          - label: "Background Type"
            name: "background_type"
            widget: "select"
            options: ["image", "video", "mux"]
            default: "image"
            hint: "Choose between a static image, Vimeo video, or Mux video background"
          - {label: "Background Image", name: "background_image", widget: "image", required: false, default: "/images/background-image.jpg", hint: "This is the main background image for the home page"}
          - {label: "Vimeo Video URL", name: "vimeo_url", widget: "string", required: false, hint: "Enter the full Vimeo URL (e.g., https://vimeo.com/123456789)"}
          - label: "Mux Video URL"
            name: "mux_url"
            widget: "string"
            required: false
            hint: "Paste your full Mux video URL (e.g., https://stream.mux.com/PLAYBACK_ID.m3u8 or .mp4)"
          - label: "Ticket Buttons"
            name: "ticket_buttons"
            widget: "list"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Is Sold Out", name: "sold_out", widget: "boolean", default: false}
              - {label: "Target", name: "target", widget: "select", options: ["_blank", "_self"], default: "_blank"}
            summary: "{{fields.text}} {{fields.sold_out | ternary '(Sold Out)' ''}}"
          - label: "Floating Buttons"
            name: "floating_buttons"
            widget: "list"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
            summary: "{{fields.text}} {{fields.visible | ternary '' '(Hidden)'}}"
          - label: "Social"
            name: "social"
            widget: "object"
            required: false
            fields:
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - label: "Partners Section"
            name: "partners_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Special thanks"}
              - label: "Partners"
                name: "partners"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
                summary: "{{fields.name}}"

      - name: "about_darklight"
        label: "About Darklight"
        file: "content/about-darklight.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "content", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}
            summary: "{{fields.title}}"

      - name: "about_resonate"
        label: "About Resonate"
        file: "content/about-resonate.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "content", widget: "markdown"}
          - label: "Performers"
            name: "performers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
            summary: "{{fields.name}}"

      - name: "faq"
        label: "FAQ Page"
        file: "content/faq-darklight.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "FAQ Items"
            name: "faqs"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
            summary: "{{fields.question}}"