backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"

# Media storage
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Dates", name: "dates", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Background Image", name: "background_image", widget: "image", required: true, default: "/images/background-image.jpg", hint: "This is the main background image for the home page"}
          - label: "Floating Buttons"
            name: "floating_buttons"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - {label: "Instagram", name: "instagram", widget: "string"}
              - {label: "Facebook", name: "facebook", widget: "string"}

      - name: "about_darklight"
        label: "About Darklight"
        file: "content/about-darklight.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "content", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Section Content", name: "content", widget: "markdown"}
            summary: "{{fields.title}}"

      - name: "about_resonate"
        label: "About Resonate"
        file: "content/about-resonate.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "content", widget: "markdown"}
          - label: "Performers"
            name: "performers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
            summary: "{{fields.name}}"

      - name: "faq"
        label: "FAQ Page"
        file: "content/faq-darklight.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "FAQ Items"
            name: "faqs"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
            summary: "{{fields.question}}"