backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"

# Media storage
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Dates", name: "dates", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
          - label: "Background Type"
            name: "background_type"
            widget: "select"
            options: ["image", "vimeo"]
            default: "image"
            hint: "Choose between a static image or a Vimeo video background"
          - {label: "Background Image", name: "background_image", widget: "image", required: false, default: "/images/background-image.jpg", hint: "This is the main background image for the home page"}
          - {label: "Vimeo Video URL", name: "vimeo_url", widget: "string", required: false, hint: "Paste your Vimeo player URL here (e.g., https://player.vimeo.com/video/123456789)"}
          - label: "Ticket Buttons"
            name: "ticket_buttons"
            widget: "list"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Is Sold Out", name: "sold_out", widget: "boolean", default: false}
              - {label: "Target", name: "target", widget: "select", options: ["_blank", "_self"], default: "_blank"}
            summary: "{{fields.text}} {{fields.sold_out | ternary '(Sold Out)' ''}}"
          - label: "Floating Buttons"
            name: "floating_buttons"
            widget: "list"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string", required: false}
              - {label: "Link", name: "link", widget: "string", required: false}
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
            summary: "{{fields.text}} {{fields.visible | ternary '' '(Hidden)'}}"
          - label: "Social"
            name: "social"
            widget: "object"
            required: false
            fields:
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - label: "Partners Section"
            name: "partners_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Special thanks"}
              - label: "Partners"
                name: "partners"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
                summary: "{{fields.name}}"

      - name: "about"
        label: "About"
        file: "content/about.md"
        fields:
          - {label: "Page Title", name: "page_title", widget: "string", default: "About & FAQ"}
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - {label: "Number", name: "number", widget: "string", hint: "e.g., 01, 02, 03"}
              - {label: "Label", name: "label", widget: "string", hint: "e.g., Darklight, FAQ, About Us"}
              - {label: "Section ID", name: "section_id", widget: "string", hint: "e.g., about-darklight, faq, about-us"}
              - {label: "Visible", name: "visible", widget: "boolean", default: true, hint: "Show this section in navigation and on page"}
            summary: "{{fields.number}} {{fields.label}} {{fields.visible | ternary '' '(Hidden)'}}"
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section ID", name: "section_id", widget: "string", hint: "Must match navigation section_id"}
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Visible", name: "visible", widget: "boolean", default: true, hint: "Show this section on the page"}
              - label: "Content Type"
                name: "content_type"
                widget: "select"
                options: ["text", "faq", "about_us"]
                default: "text"
              - label: "Content"
                name: "content"
                widget: "markdown"
                required: false
              - label: "FAQ Items"
                name: "faq_items"
                widget: "list"
                required: false
                fields:
                  - {label: "Question", name: "question", widget: "string"}
                  - {label: "Answer", name: "answer", widget: "markdown"}
                summary: "{{fields.question}}"
              - label: "About Us Items"
                name: "about_us_items"
                widget: "list"
                required: false
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Description", name: "description", widget: "markdown"}
                summary: "{{fields.name}}"
            summary: "{{fields.title}} ({{fields.content_type}}) {{fields.visible | ternary '' '(Hidden)'}}"

      - name: "about_resonate"
        label: "Resonate"
        file: "content/about-resonate.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "content", widget: "markdown"}
          - label: "Performers"
            name: "performers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
            summary: "{{fields.name}}"

      - name: "gallery"
        label: "Gallery"
        file: content/gallery.md
        fields:
          - { name: title, label: Gallery Title, widget: string }
          - label: Images
            name: images
            widget: list
            fields:
              - { name: url, label: Image, widget: image }
              - { name: caption, label: Caption, widget: string, required: false }

      - name: "installation"
        label: "Installation"
        file: "content/installation.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Installation"}
          - {label: "Image", name: "image", widget: "image", default: "/images/map.svg"}
          - {label: "Artwork Number", name: "artwork_number", widget: "string", hint: "e.g., 1, 2, 3"}
          - {label: "Artwork Name", name: "artwork_name", widget: "string", hint: "e.g., SIGNAL, LUMINOUS WAVES"}
          - {label: "Artist", name: "artist", widget: "string", hint: "e.g., Angus Muir"}
          - {label: "Sound Artist", name: "sound_artist", widget: "string", hint: "e.g., Paul Sweetman"}
          - {label: "Bio", name: "bio", widget: "markdown", hint: "Description of the artwork"}
          - {label: "Visible", name: "visible", widget: "boolean", default: true, hint: "Show this page"}